### PR TITLE
unit test snippets

### PR DESCRIPTION
**Pull request by paulobezerr**
- test
- describe
- setup

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @paulobezerr. Quick question: are those snippets going to use tabs? Or the editor converts them to whatever the user has configured?

Also, can we please change describe to not define a test by default?

**Comment by paulobezerr** [comment]
According to [sublime documentation](http://sublimetext.info/docs/en/extensibility/snippets.html), `TabTrigger` is an implicit key binding, so I guess that you can use any keybinding.

About `describe` trigger, I'll remove `test` macro.

Thank you for your quick answer.

**Comment by josevalim** [comment]
> According to [sublime documentation](http://sublimetext.info/docs/en/extensibility/snippets.html), `TabTrigger` is an implicit key binding, so I guess that you can use any keybinding.

Sorry, I meant to say, once I use the snippet, will it use "tabs" or "spaces" for indentation? Does it matter?

**Comment by paulobezerr** [comment]
> Sorry, I meant to say, once I use the snippet, will it use "tabs" or "spaces" for indentation? Does it matter?

I did not realize that. It adds wrong.
I pushed with tabs.

**Comment by paulobezerr** [comment]
Is there something else? :smiley:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
